#ifndef OP_CODE_HEADER_INCLUDED
#define OP_CODE_HEADER_INCLUDED

/**
 * These values are not used by users.
 */

enum OP_CODE{
	OP_START = 128,
	OP_BAUD,
	OP_CONTROL,
	OP_SAFE, 
	OP_FULL,
	OP_POWER,
	OP_SPOT,
	OP_CLEAN,
	OP_MAX,
	OP_DRIVE,
	OP_MOTORS,
	OP_LEDS,
	OP_SONG,
	OP_PLAY,
	OP_SENSORS,
	OP_DOCK,

	OP_DRIVE_DIRECT = 145,
	OP_DRIVE_PWM,

	OP_STREAM = 148,
	OP_QUERY_LIST,
	OP_PAUSE_RESUME_STREAM,

};





enum Baud {
	OP_BAUD_300 = 0,
	OP_BAUD_600,
	OP_BAUD_1200,
	OP_BAUD_2400,
	OP_BAUD_4800,
	OP_BAUD_9600,
	OP_BAUD_14400,
	OP_BAUD_19200,
	OP_BAUD_28800,
	OP_BAUD_38400,
	OP_BAUD_57600,
	OP_BAUD_115200,
};


enum SensorID {
	BUMPS_AND_WHEEL_DROPS = 7,
	WALL,
	CLIFF_LEFT,
	CLIFF_FRONT_LEFT,
	CLIFF_FRONT_RIGHT,
	CLIFF_RIGHT,
	VIRTUAL_WALL,
	WHEEL_OVERCURRENTS,
	DIRT_DETECT,
	UNUSED_BYTE,
	INFRARED_CHARACTER_OMNI,
	BUTTONS,
	DISTANCE,
	ANGLE,
	CHARGING_STATE,
	VOLTAGE,
	CURRENT,
	TEMPERATURE,
	BATTERY_CHARGE,
	BATTERY_CAPACITY,
	WALL_SIGNAL,
	CLIFF_LEFT_SIGNAL,
	CLIFF_FRONT_LEFT_SIGNAL,
	CLIFF_FRONT_RIGHT_SIGNAL,
	CLIFF_RIGHT_SIGNAL,
	UNUSED1,
	UNUSED2,
	CHARGING_SOURCE_AVAILABLE,
	OI_MODE,
	SONG_NUMBER,
	SONG_PLAYING,
	NUMBER_OF_STREAM_PACKETS,
	REQUESTED_VELOCITY,
	REQUESTED_RADIUS,
	REQUESTED_RIGHT_VELOCITY,
	REQUESTED_LEFT_VELOCITY,
	RIGHT_ENCODER_COUNTS,
	LEFT_ENCODER_COUNTS,
	LIGHT_BUMPER,
	LIGHT_BUMP_LEFT_SIGNAL,
	LIGHT_BUMP_FRONT_LEFT_SIGNAL,
	LIGHT_BUMP_CENTER_LEFT_SIGNAL,
	LIGHT_BUMP_CENTER_RIGHT_SIGNAL,
	LIGHT_BUMP_FRONT_RIGHT_SIGNAL,
	INFRARED_CHARACTER_LEFT = 52,
	INFRARED_CHARACTER_RIGHT = 53,
	LEFT_MOTOR_CURRENT = 54,
	RIGHT_MOTOR_CURRENT,
	MAIN_BRUSH_MOTOR_CURRENT,
	SIDE_BRUSH_MOTOR_CURRENT,
	STASIS,

};

#endif //#ifndef OP_CODE_HEADER_INCLUDED